name: app_taski
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter:

  uses-material-design: true

  assets:  
    - assets/images/perfil.jpg
    - assets/images/logo.jpg
    - assets/images/empty-list-image.jpg

